name: Auto Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (minimum interval for scheduled workflows)
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "tsakane28"
        git config --global user.email "wesleytsakane116.com"

    - name: Run auto commit script
      run: |
        chmod +x auto_commit.sh
        ./auto_commit.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
